### PR TITLE
Update xOP1mul10.z80

### PR DESCRIPTION
**Pull request by grosged**
Of course, these little optimizations while considering xOP1 to xOP5 will respectively always be equal $8000 to $8028 ... ;)

### CODE REVIEW

**Comment by grosged** [comment]
& what about routines.z80 ..? We may optimize inside it the same way, right ? ;)

**Comment by Zeda** [comment]
While these equates are constants at compile time, I want these routines to be general so that others may move these locations. My preferred method for such optimizations is through compiler directives, for example:
```
#if ((xOP1+1)&255)<255
    inc l
#else
    inc hl
#endif
```
It is tedious, but it is effective.

**Comment by grosged** [comment]
Ah okay, I see...I thought these equates would never change.
Yes, the "directives manner" would make it less readable

**Comment by grosged** [comment]
yeah , clever use of macros :)

**Comment by Zeda** [comment]
I reverted a bunch of the routines just because I couldn't guarantee constant inputs, but I updated a few of them with the compiler optimizations.

Thanks a bunch!

**Pull request merged**
